version: "3"
services:
  web:
    build: .
    environment: 
      - HOST=0.0.0.0
    volumes:
      - ./:/src/vue-mooc
    ports:
      - 3400:3400
      - 4300:4300
    links:
      - mongo
  mongo:
    image: mongo:4.1.6
